// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmy8kb9U0znbaEIOdhWKjrgMNLodeRHs',
    appId: '1:829138089755:web:dae0c1898b4e1b2f48c5be',
    messagingSenderId: '829138089755',
    projectId: 'miaged-quentin-guillou',
    authDomain: 'miaged-quentin-guillou.firebaseapp.com',
    storageBucket: 'miaged-quentin-guillou.appspot.com',
    measurementId: 'G-LGDXTNCRK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIvwBRDgFsjfPK9bRiVnQLSyYedVLySCs',
    appId: '1:829138089755:android:2a5b29b00c60c01c48c5be',
    messagingSenderId: '829138089755',
    projectId: 'miaged-quentin-guillou',
    storageBucket: 'miaged-quentin-guillou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ0kGXJ8eUkT7P2GbLCXX06SxWOvPxob4',
    appId: '1:829138089755:ios:b58a473a420c910648c5be',
    messagingSenderId: '829138089755',
    projectId: 'miaged-quentin-guillou',
    storageBucket: 'miaged-quentin-guillou.appspot.com',
    iosBundleId: 'com.example.miaged',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ0kGXJ8eUkT7P2GbLCXX06SxWOvPxob4',
    appId: '1:829138089755:ios:bbb241f8f878e8be48c5be',
    messagingSenderId: '829138089755',
    projectId: 'miaged-quentin-guillou',
    storageBucket: 'miaged-quentin-guillou.appspot.com',
    iosBundleId: 'com.example.miaged.RunnerTests',
  );
}
